version: '3.4'
services:
  db:
    image: postgres:latest
    container_name: postgres_acm
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
